spring:
  application:
    name: DEV-TRACKER

server:
  port: ${SERVER_PORT:8000}

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics

  endpoint:
    health:
      show-details: always  # or 'when_authorized' if you later add security

  health:
    probes:
      enabled: true  # enables /actuator/health/liveness and readiness probes

  metrics:
    tags:
      application: DEV-TRACKER

info:
  app:
    name: DEV-TRACKER
    version: 1.0.0
    description: Production-ready backend for Dev-Tracker Application
