name: Feature Branch Continues Integration
run-name: ${{ github.actor }} started CI for feature branch ${{ github.ref }} by making ${{ github.event_name }} request 🚀
on:
  push:
    branches:
      - 'feature/**'
jobs:
  Feature-Branch-CI:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      # Check Out Repository
      - name: 📥 Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      # Setup JDK
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      # Compile and Build
      - name: 🏗️ Compile and Build Application
        run: mvn -B package --file pom.xml
      - run: echo "📦 Application compiled and built successfully"
      # Run Unit Tests
      - name: 🧪 Run Unit-Tests
        run: mvn test
      - run: echo "✅ Successfully completed unit tests!"

      - run: echo "🍏 This job's status is ${{ job.status }}."
