name: Feature Branch Continuous Integration
run-name: ${{github.actor }} has triggered this by ${{ github.event_name }} event
on:
  push:
    branches:
      - 'feature/**'
jobs:
  Continuous-Integration:
    runs-on: ubuntu-latest
    steps:
      - name: Testing Feature Branch CI
        run: echo "Running this JOB"