name: Basic workflow
run-name: ${{ github.actor }} started workflow in GitHub Actions 🚀
on:
  workflow_dispatch:

jobs:
  Greet-from-bash:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello from  ${{ github.actor }}"
      - run: echo "This workflow was triggered using ${{ github.event_name }} event"
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
  Greet-from-python:
    runs-on: ubuntu-latest
    steps:
      - run: print("Hello from ${{github.actor}} using python shell")
        shell: python
